# Generated by Django 2.1.3 on 2019-04-28 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=15)),
                ('field_type', models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Date', 'Date')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NumberField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Field')),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Field')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RiskType'),
        ),
        migrations.AddField(
            model_name='datefield',
            name='field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Field'),
        ),
    ]
